# This is a basic workflow to help you get started with Actions

name: Enable repo branch protection

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      ORG_NAME:
        description: 'Provide the organization name'
        required: true
        type: string
      API_TOKEN:
        description: 'TOKEN having the right permission to target repositories'
        required: true
        type: string
      BranchName:
        description: 'branch name, only if its other than "main"'
        required: false
        type: string
      GithubApiUrl:
        description: 'API URL, only if its other than "https://api.github.com"'
        required: false
        type: string
      

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Execute bash script
        run: |
          echo Executing enable-repo-branch-protection.sh,
          chmod +x $GITHUB_WORKSPACE/enable-repo-branch-protection.sh
          $GITHUB_WORKSPACE/enable-repo-branch-protection.sh $ORG_NAME $API_TOKEN.
